"""initial schema

Revision ID: 19ffdfdbf696
Revises: 
Create Date: 2026-07-14 03:24:28.487674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ffdfdbf696'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weekly_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('request_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appeal_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'published', 'locked', name='weekly_cycle_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('default_shift_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('default_off_day_type', sa.Enum('fixed', 'flexible', name='off_day_type'), nullable=False),
    sa.Column('default_off_day', sa.Integer(), nullable=True),
    sa.Column('default_off_days_per_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_shift_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_slot_start', sa.Time(), nullable=False),
    sa.Column('time_slot_end', sa.Time(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('min_agents_required', sa.Integer(), nullable=False),
    sa.Column('is_peak', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_cycle_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.Enum('solver', 'manual', name='generated_by'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'locked', name='roster_status'), nullable=False),
    sa.ForeignKeyConstraint(['week_cycle_id'], ['weekly_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_leave_days_allotted', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('leave_days_taken', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('half_days_taken', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'year', name='uq_leave_balance_agent_year')
    )
    op.create_table('roster_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('skill_covered_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('solver', 'manual_override', name='assignment_source'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_templates.id'], ),
    sa.ForeignKeyConstraint(['skill_covered_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satisfaction_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('agent', 'manager', name='user_role'), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weekly_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_cycle_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('off_day', 'leave_full', 'leave_half', 'leave_multi', 'shift_change', 'overtime', 'other', name='request_type'), nullable=False),
    sa.Column('requested_start_date', sa.Date(), nullable=False),
    sa.Column('requested_end_date', sa.Date(), nullable=True),
    sa.Column('half_day_portion', sa.Enum('first_half', 'second_half', name='half_day_portion'), nullable=True),
    sa.Column('requested_shift_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'appealed', name='request_status'), nullable=False),
    sa.Column('denial_reason', sa.String(length=255), nullable=True),
    sa.Column('submitted_via', sa.Enum('form', 'ai_parsed', name='submitted_via'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['requested_shift_id'], ['shift_templates.id'], ),
    sa.ForeignKeyConstraint(['week_cycle_id'], ['weekly_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_request_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('appeal_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='appeal_status'), nullable=False),
    sa.Column('manager_response', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_request_id'], ['weekly_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflict_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_agent_id', sa.Integer(), nullable=True),
    sa.Column('unmet_request_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='conflict_severity'), nullable=False),
    sa.ForeignKeyConstraint(['affected_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ),
    sa.ForeignKeyConstraint(['unmet_request_id'], ['weekly_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflict_reports')
    op.drop_table('audit_log')
    op.drop_table('appeals')
    op.drop_table('weekly_requests')
    op.drop_table('users')
    op.drop_table('satisfaction_metrics')
    op.drop_table('roster_assignments')
    op.drop_table('leave_balances')
    op.drop_table('agent_skills')
    op.drop_table('rosters')
    op.drop_table('coverage_requirements')
    op.drop_table('agents')
    op.drop_table('weekly_cycles')
    op.drop_table('skills')
    op.drop_table('shift_templates')
    # ### end Alembic commands ###
