"""add solver_weights table

Revision ID: 9ad49dd9f32d
Revises: 19ffdfdbf696
Create Date: 2026-07-14 04:55:33.875841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad49dd9f32d'
down_revision: Union[str, None] = '19ffdfdbf696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solver_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('off_day_request_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('default_off_day_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('leave_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('shift_change_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fairness_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solver_weights')
    # ### end Alembic commands ###
